<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">         
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headTitle('UMTIK 2018')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>


        <link href="<?php echo $this->basePath('css/custom.css') ?>" rel="stylesheet" type="text/css">

        <link href="<?php echo $this->basePath('css/color.css') ?>" rel="stylesheet" type="text/css">

        <link href="<?php echo $this->basePath('css/bootstrap.css') ?>" rel="stylesheet" type="text/css">

        <link href="<?php echo $this->basePath('css/jquery.bxslider.css') ?>" rel="stylesheet" type="text/css">

        <link href="<?php echo $this->basePath('css/hexa-style.css') ?>" rel="stylesheet" type="text/css">

        <link href="<?php echo $this->basePath('css/component.css') ?>" rel="stylesheet" type="text/css" />

        <link href="<?php echo $this->basePath('css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css">

        <link href='http://fonts.googleapis.com/css?family=Signika:300,400,600,700' rel='stylesheet' type='text/css'>

        <link rel="icon" href="<?php echo $this->basePath('images/favicon.ico') ?>" type="image/x-icon">
        
        <link href="<?php echo $this->basePath('css/lightslider.css')?>" type="text/css" rel="stylesheet" />  
        
        <link href="<?php echo $this->basePath('css/inline_custom.css')?>" type="text/css" rel="stylesheet" />                  



    </head>
    <!--The #page-top ID is part of the scrolling feature.
    The data-spy and data-target are part of the built-in Bootstrap scrollspy function.-->
    <body id="body" data-spy="scroll" data-target=".one-page-header" class="demo-lightbox-gallery">

        
        <?php echo $this->content; ?>
        
        <script src="<?php echo $this->basePath('js/jquery-1.11.3.min.js')?>"></script>
        
        <script src="<?php echo $this->basePath('js/jquery-ui.js')?>"></script>

        <script src="<?php echo $this->basePath('js/bootstrap.min.js')?>"></script>

        <script src="<?php echo $this->basePath('js/respond.js')?>"></script>

        <script src="<?php echo $this->basePath('js/jquery.bxslider.min.js')?>"></script>

        <script src="<?php echo $this->basePath('js/jquery.vide.js')?>"></script>

        <script src="<?php echo $this->basePath('js/jquery.final-countdown.js')?>"></script>
        
        <script src="<?php echo $this->basePath('js/kinetic.js')?>"></script>

        <script src="<?php echo $this->basePath('js/fitvid.js')?>"></script>

        <script src="<?php echo $this->basePath('js/custom.js')?>"></script>

        <script src="<?php echo $this->basePath('js/umtik_inline.js')?>"></script>

        <script src="<?php echo $this->basePath('js/lightslider.js')?>"></script>

        <script src="<?php echo $this->basePath('js/html5.js') ?>"></script>

    </body>
</html>
